pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo 'Construindo a imagem...'
        sh 'docker build -t hello-world-app:latest .'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Fazendo deploy no Kubernetes...'
        sh 'kubectl apply -f k8s/'
      }
    }
  }
}